// PetEngine.js — pure vanilla game loop for the transparent overlay.
// Physics, the random-AI state machine, and sprite slicing all live here so the
// React layer never re-renders for animation (see design.md §2.B).

// All sheets in public/sprites are generated by tools/generate_sprites.mjs as
// an 8-column x 6-row grid of equal frames (64x64 px).
const SHEET_COLS = 8;
const SHEET_ROWS = 6;

// ---------------------------------------------------------------------------
// Sprite alpha masks — per-sheet, per-frame tight boxes of the visible pixels,
// so hit boxes hug the drawn pet instead of the (mostly transparent) frame.
// Built lazily once per sheet from the image's alpha channel.
// ---------------------------------------------------------------------------
const ALPHA_MIN = 8; // ignore near-invisible antialiasing fringe
const MASKS = new WeakMap(); // Image -> { fw, fh, frames[row][col] = {x,y,w,h}|null }

function buildMask(img) {
  const fw = Math.floor(img.naturalWidth / SHEET_COLS);
  const fh = Math.floor(img.naturalHeight / SHEET_ROWS);
  const canvas = document.createElement("canvas");
  canvas.width = img.naturalWidth;
  canvas.height = img.naturalHeight;
  const ctx = canvas.getContext("2d");
  ctx.drawImage(img, 0, 0);
  const { data } = ctx.getImageData(0, 0, canvas.width, canvas.height);
  const frames = [];
  for (let row = 0; row < SHEET_ROWS; row++) {
    const cols = [];
    for (let col = 0; col < SHEET_COLS; col++) {
      let minX = fw, minY = fh, maxX = -1, maxY = -1;
      for (let y = 0; y < fh; y++) {
        for (let x = 0; x < fw; x++) {
          const a = data[((row * fh + y) * canvas.width + col * fw + x) * 4 + 3];
          if (a > ALPHA_MIN) {
            if (x < minX) minX = x;
            if (y < minY) minY = y;
            if (x > maxX) maxX = x;
            if (y > maxY) maxY = y;
          }
        }
      }
      cols.push(
        maxX < 0
          ? null
          : { x: minX, y: minY, w: maxX - minX + 1, h: maxY - minY + 1 },
      );
    }
    frames.push(cols);
  }
  return { fw, fh, frames };
}

function getMask(img) {
  if (!img || !img.complete || !img.naturalWidth) return null;
  let mask = MASKS.get(img);
  if (!mask) {
    try {
      mask = buildMask(img);
    } catch {
      return null; // e.g. tainted canvas; callers fall back to the full box
    }
    MASKS.set(img, mask);
  }
  return mask;
}

// ---------------------------------------------------------------------------
// Shared world state. One copy, read by every pet each frame.
// ---------------------------------------------------------------------------
export const world = {
  // Behavior #4: lowest walkable level = top of the taskbar. Rust sends the real
  // value via "floor_updated"; this inset is only a fallback until then.
  // 56px clears a default Windows 11 taskbar (~48px) plus a couple px margin.
  screenFloor: window.innerHeight - 56,
  platforms: [], // { x, y, w, h } — icon tops the pet can stand on
  obstacles: [], // { x, y, w, h } — full icon boxes that block horizontal movement
  // Icons are only real to the pet while the desktop is the foreground "page";
  // over other windows it just walks the taskbar floor. Rust drives this via
  // the desktop_state_updated event.
  desktopActive: true,
};

let settings = {
  iconRole: "mixed", // "platform" | "obstacle" | "mixed"
  useIconsAsPlatforms: true,
  speed: 1.5,
  width: 80,
  height: 80,
  // Roster of individual pets, each with its own sprite and click action:
  // { id, petType, petColor, clickAction: "say"|"app", phrase, appCommand }
  pets: [
    {
      id: "default",
      petType: "dog",
      petColor: "brown",
      clickAction: "say",
      phrase: "",
      appCommand: "",
    },
  ],
};

export function setSettings(next) {
  settings = { ...settings, ...next };
}
export function getSettings() {
  return settings;
}

// Build collision geometry from raw icon rects per the iconRole setting (§3.C).
// Rust reports icon rects in PHYSICAL pixels; the canvas works in CSS pixels,
// so scale by devicePixelRatio or the pet floats beside icons at 125%/150% DPI.
let lastIconRects = [];
export function buildPlatforms(iconRects) {
  lastIconRects = iconRects;
  world.platforms = [];
  world.obstacles = [];
  if (!settings.useIconsAsPlatforms || !world.desktopActive) return;
  const dpr = window.devicePixelRatio || 1;
  for (const r of iconRects) {
    const x = r.x / dpr;
    const y = r.y / dpr;
    const w = r.w / dpr;
    const h = r.h / dpr;
    if (settings.iconRole !== "obstacle") {
      world.platforms.push({ x, y, w, h: 4 });
    }
    if (settings.iconRole !== "platform") {
      world.obstacles.push({ x, y, w, h });
    }
  }
  world.platforms = mergeNarrowGaps(world.platforms, settings.width);
}

// Bridge gaps between same-row platforms that are narrower than the pet, so
// the pet can't slip between neighboring desktop icons. groundBeneath() tests
// the feet CENTER point, so any gap wider than 0 could otherwise swallow it.
const ROW_Y_TOLERANCE = 8; // icon tops within this many px count as one row
function mergeNarrowGaps(platforms, petWidth) {
  const sorted = [...platforms].sort((a, b) => a.y - b.y || a.x - b.x);
  const merged = [];
  for (const p of sorted) {
    const prev = merged[merged.length - 1];
    const sameRow = prev && Math.abs(p.y - prev.y) <= ROW_Y_TOLERANCE;
    const gap = prev ? p.x - (prev.x + prev.w) : Infinity;
    if (sameRow && gap < petWidth) {
      // Extend the previous platform across the gap (gap may be negative if
      // the rects already overlap).
      prev.w = Math.max(prev.w, p.x + p.w - prev.x);
    } else {
      merged.push({ ...p });
    }
  }
  return merged;
}

// Re-derive geometry after a settings change (iconRole / useIconsAsPlatforms).
export function rebuildPlatforms() {
  buildPlatforms(lastIconRects);
}

// Toggle icon interaction with desktop visibility. Clearing the geometry makes
// pets standing on icons fall back to the taskbar floor via normal gravity.
export function setDesktopActive(active) {
  const next = !!active;
  if (world.desktopActive === next) return;
  world.desktopActive = next;
  rebuildPlatforms();
}

export function setFloor(taskbarTop) {
  // Rust reports the work-area bottom in PHYSICAL pixels. The canvas draws in
  // CSS pixels, so divide by devicePixelRatio (1 at 100% scaling, 1.25/1.5 etc.
  // at higher DPI). Clamp into the visible canvas so the pet is never below it.
  if (Number.isFinite(taskbarTop) && taskbarTop > 0) {
    const dpr = window.devicePixelRatio || 1;
    const cssFloor = Math.round(taskbarTop / dpr);
    world.screenFloor = Math.min(cssFloor, window.innerHeight);
  }
}

// ---------------------------------------------------------------------------
// Animation maps (sprite sheet rows). Every generated sheet is the same
// 8-column x 6-row layout (see tools/generate_sprites.mjs), so one map fits
// all sprites. `frameDelay` = engine ticks (~60/s) per animation frame.
// ---------------------------------------------------------------------------
const DEFAULT_ANIM = {
  idle: { row: 0, totalFrames: 8, startFrame: 0, loop: true, frameDelay: 9 },
  walk: { row: 1, totalFrames: 8, startFrame: 0, loop: true, frameDelay: 5 },
  sit: { row: 2, totalFrames: 8, startFrame: 0, loop: true, frameDelay: 11 },
  sleep: { row: 3, totalFrames: 8, startFrame: 0, loop: true, frameDelay: 16 },
  jump: { row: 4, totalFrames: 8, startFrame: 0, loop: false, frameDelay: 5 },
  // Feeding reaction (trash collectors): plays the row-4 chomp cycle on a
  // timer instead of the jump row's vy-driven frame mapping.
  chomp: { row: 4, totalFrames: 8, startFrame: 0, loop: true, frameDelay: 4 },
  look: { row: 5, totalFrames: 8, startFrame: 0, loop: true, frameDelay: 8 },
};

// Pet types that eat file drops (see getTrashPetAt / the canvas drop handler).
const TRASH_PET_TYPES = new Set(["shark", "pacman"]);

function animMapFor() {
  return DEFAULT_ANIM;
}

// Map a behavior state to an animation key.
function animForState(state) {
  switch (state) {
    case "WALKING_LEFT":
    case "WALKING_RIGHT":
      return "walk";
    case "SLEEP":
      return "sleep";
    case "SIT":
      return "sit";
    case "JUMPING":
    case "FALLING":
    case "DRAGGING": // vy is 0 while held, so this shows the mid-air float pose
      return "jump";
    case "CHOMP":
      return "chomp";
    case "LOOKING":
      return "look";
    case "IDLE":
    default:
      return "idle";
  }
}

// ---------------------------------------------------------------------------
// Random helpers
// ---------------------------------------------------------------------------
const rand = (min, max) => min + Math.random() * (max - min);
const pickRandom = (arr) => arr[Math.floor(Math.random() * arr.length)];

// Little reactions for hovering the cursor over a pet without clicking.
const HOVER_EMOTES = [":D", ":)", "XD", "^_^", ":3", "o_o", "!", "♪"];
const EMOTE_COOLDOWN_MS = 4000; // per pet, so wiggling the cursor doesn't spam
const EMOTE_DURATION_MS = 1600;

const ACTION_WEIGHTS = {
  WALKING_LEFT: 3,
  WALKING_RIGHT: 3,
  JUMPING: 1,
  IDLE: 2,
  SIT: 2,
  SLEEP: 1,
};
function weightedRandom(weights) {
  const total = Object.values(weights).reduce((a, b) => a + b, 0);
  let roll = Math.random() * total;
  for (const [key, w] of Object.entries(weights)) {
    if ((roll -= w) <= 0) return key;
  }
  return Object.keys(weights)[0];
}

// ---------------------------------------------------------------------------
// DesktopPet
// ---------------------------------------------------------------------------
let nextId = 1;

export class DesktopPet {
  constructor(x, y, spriteSheet, spriteKey = "") {
    this.id = nextId++;
    this.x = x;
    this.y = y;
    this.w = settings.width;
    this.h = settings.height;
    this.spriteSheet = spriteSheet;
    // "{type}_{color}" — selects this pet's per-sprite animation layout.
    this.spriteKey = spriteKey;
    this.anim = animMapFor(spriteKey);

    // Frame size = sheet / grid. Fall back to 64 until the image loads.
    this.frameWidth = spriteSheet?.width ? spriteSheet.width / SHEET_COLS : 64;
    this.frameHeight = spriteSheet?.height ? spriteSheet.height / SHEET_ROWS : 64;

    this.vy = 0;
    this.gravity = 0.6;
    this.speed = settings.speed;

    this.state = "FALLING";
    this.facing = 1; // 1 right, -1 left

    // Animation frame cycling
    this.currentFrame = 0;
    this.tick = 0;
    this.animKey = "idle"; // tracked so a state change restarts its animation

    // AI / interaction timers (ms, performance.now based)
    this.nextDecisionAt = performance.now() + rand(800, 2000);
    this.lookUntil = 0;
    this.chompUntil = 0;
    this.bubble = null; // { text, expires, emote? }
    this.nextEmoteAt = 0; // hover-emote cooldown
  }

  refreshFrameSize() {
    if (this.spriteSheet?.width) {
      this.frameWidth = this.spriteSheet.width / SHEET_COLS;
      this.frameHeight = this.spriteSheet.height / SHEET_ROWS;
    }
  }

  // ----- physics helpers (design.md §2.B) -----
  groundBeneath(nextY) {
    const feetX = this.x + this.w / 2;
    let ground = world.screenFloor;
    for (const p of world.platforms) {
      const overTop = feetX >= p.x && feetX <= p.x + p.w;
      const landing = this.y + this.h <= p.y && nextY + this.h >= p.y;
      if (overTop && landing && p.y < ground) ground = p.y;
    }
    return ground;
  }

  blockedHorizontally(nextX) {
    for (const o of world.obstacles) {
      const vOverlap = this.y + this.h > o.y && this.y < o.y + o.h;
      const willEnter = nextX + this.w > o.x && nextX < o.x + o.w;
      const wasOutside = this.x + this.w <= o.x || this.x >= o.x + o.w;
      if (vOverlap && willEnter && wasOutside) return true;
    }
    return false;
  }

  tryJumpOrTurn() {
    // If grounded, hop to try mounting the icon; physics resolves the landing.
    if (this.vy === 0) {
      this.vy = -11;
      this.state = "JUMPING";
    } else {
      // Already airborne and still blocked — reverse.
      this.facing *= -1;
    }
  }

  // ----- drag & drop -----
  startDrag(px, py) {
    this.state = "DRAGGING";
    this.vy = 0;
    this.dragOffsetX = px - this.x;
    this.dragOffsetY = py - this.y;
  }

  dragTo(px, py) {
    this.x = Math.max(0, Math.min(px - this.dragOffsetX, window.innerWidth - this.w));
    this.y = Math.max(0, Math.min(py - this.dragOffsetY, world.screenFloor - this.h));
  }

  // Release: if an icon top (or the floor) is just under the pet's feet, snap
  // onto it as a deliberate "placement"; otherwise let gravity take over.
  drop(now) {
    const SNAP = 40; // px below the feet that still counts as "placed on it"
    const feetX = this.x + this.w / 2;
    const feetY = this.y + this.h;
    let landing = null;
    for (const p of world.platforms) {
      const overTop = feetX >= p.x && feetX <= p.x + p.w;
      const near = p.y >= feetY - 12 && p.y <= feetY + SNAP;
      if (overTop && near && (landing === null || p.y < landing)) landing = p.y;
    }
    if (landing === null && world.screenFloor <= feetY + SNAP) {
      landing = world.screenFloor;
    }

    if (landing !== null) {
      this.y = landing - this.h;
      this.vy = 0;
      this.state = "IDLE";
      this.nextDecisionAt = now + rand(1500, 4000);
    } else {
      this.vy = 0;
      this.state = "FALLING";
    }
  }

  // ----- interaction (Behavior #2) -----
  lookAt(cursorX) {
    this.state = "LOOKING";
    this.vy = 0;
    this.facing = cursorX < this.x + this.w / 2 ? -1 : 1;
    this.lookUntil = performance.now() + 2500;
  }

  say(text) {
    this.bubble = { text, expires: performance.now() + 3500 };
  }

  // Feeding reaction: stop and play the chomp cycle for a couple of loops.
  chomp(now) {
    this.state = "CHOMP";
    this.vy = 0;
    this.chompUntil = now + 1400;
  }

  // Hovering (no click): flash a little emote and, when not busy walking or
  // airborne, turn to face the cursor. Rate-limited per pet.
  emoteAtCursor(cursorX, now) {
    if (this.state === "DRAGGING" || now < this.nextEmoteAt) return;
    this.nextEmoteAt = now + EMOTE_COOLDOWN_MS;
    // Don't stomp a real speech bubble that's still visible.
    if (!this.bubble || this.bubble.expires <= now || this.bubble.emote) {
      this.bubble = {
        text: pickRandom(HOVER_EMOTES),
        expires: now + EMOTE_DURATION_MS,
        emote: true,
      };
    }
    if (this.state === "IDLE" || this.state === "SIT" || this.state === "LOOKING") {
      this.facing = cursorX < this.x + this.w / 2 ? -1 : 1;
    }
  }

  // Sheet cell (row/col) of the frame currently on screen — mirrors draw().
  frameCell() {
    const cfg = this.anim[animForState(this.state)];
    const col =
      Math.min(this.currentFrame, cfg.totalFrames - 1) + (cfg.startFrame || 0);
    return { row: cfg.row, col };
  }

  // Tight box around the visible pixels of the current frame, in CSS px
  // (mirrored when facing left). Falls back to the full w×h box until the
  // sheet has loaded.
  visibleRect() {
    const mask = getMask(this.spriteSheet);
    if (mask) {
      const { row, col } = this.frameCell();
      const fr = mask.frames[row]?.[col];
      if (fr) {
        const sx = this.w / mask.fw;
        const sy = this.h / mask.fh;
        const left = this.facing === -1 ? mask.fw - (fr.x + fr.w) : fr.x;
        return {
          x: this.x + left * sx,
          y: this.y + fr.y * sy,
          w: fr.w * sx,
          h: fr.h * sy,
        };
      }
    }
    return { x: this.x, y: this.y, w: this.w, h: this.h };
  }

  hitTest(px, py) {
    const r = this.visibleRect();
    return px >= r.x && px <= r.x + r.w && py >= r.y && py <= r.y + r.h;
  }

  // ----- AI brain (Behavior #3) -----
  decideNextAction(now) {
    if (this.state === "DRAGGING") return;
    if (this.state === "LOOKING" && now < this.lookUntil) return;
    if (this.state === "CHOMP" && now < this.chompUntil) return;
    if (this.state === "FALLING" || this.state === "JUMPING") return;
    if (now < this.nextDecisionAt) return;

    const next = weightedRandom(ACTION_WEIGHTS);
    this.state = next;
    if (next === "JUMPING") this.vy = -12;
    if (next === "WALKING_LEFT") this.facing = -1;
    if (next === "WALKING_RIGHT") this.facing = 1;

    const dwell =
      next === "SLEEP"
        ? rand(6000, 12000)
        : next === "SIT"
          ? rand(3000, 7000)
          : rand(1200, 4000);
    this.nextDecisionAt = now + dwell;
  }

  // ----- per-frame update -----
  update(now) {
    this.decideNextAction(now);

    if (this.state === "DRAGGING") {
      // Position comes from the cursor (dragTo); no physics, no AI.
      this.animate();
      return;
    }

    if (this.state === "FALLING" || this.state === "JUMPING") {
      this.vy += this.gravity;
      const nextY = this.y + this.vy;
      const ground = this.groundBeneath(nextY);
      // Allow some horizontal drift while airborne (so jumps cover ground).
      const driftX = this.x + this.facing * this.speed;
      if (!this.blockedHorizontally(driftX)) this.x = driftX;

      if (this.vy > 0 && nextY + this.h >= ground) {
        this.y = ground - this.h;
        this.vy = 0;
        this.state = "IDLE";
        this.nextDecisionAt = now + rand(400, 1500);
      } else {
        this.y = nextY;
      }
    } else if (this.state === "WALKING_LEFT" || this.state === "WALKING_RIGHT") {
      const dir = this.state === "WALKING_LEFT" ? -1 : 1;
      this.facing = dir;
      const nextX = this.x + dir * this.speed;

      if (this.blockedHorizontally(nextX)) {
        this.tryJumpOrTurn();
      } else {
        this.x = nextX;
        // Walked off the edge of a platform?
        if (this.y + this.h < this.groundBeneath(this.y + 1)) {
          this.state = "FALLING";
        }
      }
      // Bounce off screen edges.
      if (this.x < 0) {
        this.x = 0;
        this.state = "WALKING_RIGHT";
      }
      if (this.x + this.w > window.innerWidth) {
        this.x = window.innerWidth - this.w;
        this.state = "WALKING_LEFT";
      }
    } else if (this.state === "LOOKING") {
      if (now >= this.lookUntil) {
        this.state = "IDLE";
        this.nextDecisionAt = now;
      }
    } else if (this.state === "CHOMP") {
      if (now >= this.chompUntil) {
        this.state = "IDLE";
        this.nextDecisionAt = now + rand(800, 2000);
      }
    } else {
      // IDLE / SIT / SLEEP — make sure gravity still glues us to the ground if
      // the floor moved (e.g. taskbar height changed, icon removed).
      const ground = this.groundBeneath(this.y + 1);
      if (this.y + this.h < ground - 1) this.state = "FALLING";
      else this.y = ground - this.h;
    }

    this.animate();
  }

  animate() {
    const key = animForState(this.state);
    const cfg = this.anim[key];

    // Restart the cycle whenever the animation changes — otherwise a state
    // switch mid-row would keep a stale frame index and visibly stutter.
    if (key !== this.animKey) {
      this.animKey = key;
      this.currentFrame = 0;
      this.tick = 0;
    }

    // Airborne frames follow vertical velocity instead of a timer so the pose
    // always matches the arc: crouch -> launch -> rise -> peak -> fall.
    if (key === "jump") {
      const vy = this.vy;
      this.currentFrame =
        vy < -8 ? 1 : vy < -4 ? 2 : vy < -1 ? 3 : vy < 1 ? 4 : vy < 5 ? 5 : 6;
      return;
    }

    this.tick++;
    if (this.tick >= cfg.frameDelay) {
      this.tick = 0;
      this.currentFrame++;
      if (this.currentFrame >= cfg.totalFrames) {
        this.currentFrame = cfg.loop ? 0 : cfg.totalFrames - 1;
      }
    }
  }

  draw(ctx) {
    if (!this.spriteSheet || !this.spriteSheet.complete) return;
    const cfg = this.anim[animForState(this.state)];
    const startOffset = cfg.startFrame || 0;
    const frameIndex = Math.min(this.currentFrame, cfg.totalFrames - 1);
    const sx = (frameIndex + startOffset) * this.frameWidth;
    const sy = cfg.row * this.frameHeight;

    // Snap destination to whole pixels so pixel art doesn't shimmer as the pet
    // moves at sub-pixel speeds (part of the crisp vscode-pets look).
    const dx = Math.round(this.x);
    const dy = Math.round(this.y);

    if (this.facing === -1) {
      // Flip horizontally to walk/look left.
      ctx.save();
      ctx.translate(dx + this.w, dy);
      ctx.scale(-1, 1);
      ctx.drawImage(
        this.spriteSheet,
        sx,
        sy,
        this.frameWidth,
        this.frameHeight,
        0,
        0,
        this.w,
        this.h,
      );
      ctx.restore();
    } else {
      ctx.drawImage(
        this.spriteSheet,
        sx,
        sy,
        this.frameWidth,
        this.frameHeight,
        dx,
        dy,
        this.w,
        this.h,
      );
    }
  }
}

// ---------------------------------------------------------------------------
// Engine controller — owns the canvas, the pet array, and the rAF loop.
// ---------------------------------------------------------------------------
export class PetEngine {
  constructor(canvas) {
    this.canvas = canvas;
    this.ctx = canvas.getContext("2d");
    this.ctx.imageSmoothingEnabled = false; // crisp pixel art
    this.pets = [];
    this.spriteCache = new Map(); // url -> Image (load once, design.md §4)
    this.running = false;
    this.rafId = null;
    this.phrases = [];
    // Called each frame with the current pet list so React can position bubbles
    // and Rust can be told the hit-boxes.
    this.onFrame = null;
    // Called when a clicked pet's action is "open an app" / "launch Claude
    // Code" (wired to the open_app / launch_claude Tauri commands by
    // CanvasApp). Both receive the pet so failures can show as a bubble.
    this.onOpenApp = null;
    this.onLaunchClaude = null;
    // Drag bookkeeping: which pet is held, and where the press started (to
    // tell a click apart from a drag on release).
    this.draggedPet = null;
    this.dragStart = { x: 0, y: 0 };
    this.dragMoved = false;
  }

  setPhrases(phrases) {
    if (Array.isArray(phrases) && phrases.length) this.phrases = phrases;
  }

  resize() {
    this.canvas.width = window.innerWidth;
    this.canvas.height = window.innerHeight;
    // Resizing the canvas resets context state, so re-disable smoothing here.
    // Nearest-neighbor keeps pixel art crisp (like the vscode-pets look).
    this.ctx.imageSmoothingEnabled = false;
  }

  loadSprite(url) {
    if (this.spriteCache.has(url)) return this.spriteCache.get(url);
    const img = new Image();
    img.src = url;
    img.onload = () => {
      // Once loaded, fix up frame sizes for any pet using this sheet.
      for (const p of this.pets) {
        if (p.spriteSheet === img) p.refreshFrameSize();
      }
    };
    this.spriteCache.set(url, img);
    return img;
  }

  getTopmostPetAt(cx, cy) {
    for (let i = this.pets.length - 1; i >= 0; i--) {
      const pet = this.pets[i];
      if (pet.hitTest(cx, cy)) return pet;
    }
    return null;
  }

  getCursorForPoint(cx, cy) {
    if (this.draggedPet) return "grabbing";
    return this.getTopmostPetAt(cx, cy) ? "pointer" : "default";
  }

  // Topmost trash-collector pet under a file-drop point. Drops are coarser
  // than clicks, so allow a margin around the visible pixels.
  getTrashPetAt(cx, cy) {
    const MARGIN = 24;
    for (let i = this.pets.length - 1; i >= 0; i--) {
      const pet = this.pets[i];
      if (!TRASH_PET_TYPES.has(pet.config?.petType)) continue;
      const r = pet.visibleRect();
      if (
        cx >= r.x - MARGIN &&
        cx <= r.x + r.w + MARGIN &&
        cy >= r.y - MARGIN &&
        cy <= r.y + r.h + MARGIN
      ) {
        return pet;
      }
    }
    return null;
  }

  // Reconcile the live pets against the configured roster. Matching by config
  // id keeps existing pets (and their positions) across settings changes; only
  // genuinely new entries spawn, and removed entries despawn.
  syncPets(petConfigs = getSettings().pets || []) {
    const s = getSettings();
    const byId = new Map(this.pets.map((p) => [p.config?.id, p]));
    this.pets = petConfigs.map((cfg) => {
      const spriteKey = `${cfg.petType}_${cfg.petColor}`;
      const sprite = this.loadSprite(`/sprites/${spriteKey}.png`);
      let pet = byId.get(cfg.id);
      if (!pet) {
        const x = rand(50, Math.max(60, window.innerWidth - 150));
        pet = new DesktopPet(x, 0, sprite, spriteKey);
      }
      pet.config = cfg;
      pet.spriteSheet = sprite;
      pet.spriteKey = spriteKey;
      pet.anim = animMapFor(spriteKey);
      pet.w = s.width;
      pet.h = s.height;
      pet.speed = s.speed;
      pet.refreshFrameSize();
      return pet;
    });
    // Don't keep dragging a pet that was just despawned.
    if (this.draggedPet && !this.pets.includes(this.draggedPet)) {
      this.draggedPet = null;
    }
  }

  // ----- mouse events forwarded from the Rust hook (Behavior #2 + drag) -----
  // Press: pick up the topmost pet under the cursor. Whether this was a click
  // or a drag is decided on release by how far the cursor traveled.
  handleMouseDown(cx, cy) {
    const pet = this.getTopmostPetAt(cx, cy);
    if (pet) {
      this.draggedPet = pet;
      this.dragStart = { x: cx, y: cy };
      this.dragMoved = false;
      pet.startDrag(cx, cy);
      return true;
    }
    return false;
  }

  handleMouseMove(cx, cy) {
    const pet = this.draggedPet;
    if (!pet) {
      // Hover without a click: let the pet under the cursor react.
      const hovered = this.getTopmostPetAt(cx, cy);
      if (hovered) hovered.emoteAtCursor(cx, performance.now());
      return;
    }
    if (Math.abs(cx - this.dragStart.x) > 4 || Math.abs(cy - this.dragStart.y) > 4) {
      this.dragMoved = true;
    }
    if (this.dragMoved) pet.dragTo(cx, cy);
  }

  handleMouseUp(cx, cy) {
    const pet = this.draggedPet;
    if (!pet) return;
    this.draggedPet = null;
    if (!this.dragMoved) {
      // A stationary press-and-release is a click: look at the cursor, then
      // run this pet's configured interaction (the pet never actually moved,
      // so no drop physics needed).
      pet.lookAt(cx);
      const cfg = pet.config || {};
      // Sparky is hardcoded: clicking the Claude mascot always opens Claude
      // Code in a terminal, whatever an old config says.
      if (cfg.petType === "sparky" || cfg.clickAction === "claude") {
        if (cfg.phrase) pet.say(cfg.phrase);
        if (this.onLaunchClaude) this.onLaunchClaude(pet);
      } else if (cfg.clickAction === "app" && cfg.appCommand) {
        if (cfg.phrase) pet.say(cfg.phrase);
        if (this.onOpenApp) this.onOpenApp(cfg.appCommand, pet);
      } else if (cfg.phrase) {
        pet.say(cfg.phrase);
      } else if (this.phrases.length) {
        pet.say(pickRandom(this.phrases));
      }
      return;
    }
    pet.dragTo(cx, cy);
    pet.drop(performance.now());
  }

  start() {
    if (this.running) return;
    this.running = true;
    const loop = () => {
      if (!this.running) return;
      const now = performance.now();
      this.ctx.clearRect(0, 0, this.canvas.width, this.canvas.height);
      for (const pet of this.pets) {
        pet.update(now);
        pet.draw(this.ctx);
      }
      if (this.onFrame) this.onFrame(this.pets, now);
      this.rafId = requestAnimationFrame(loop);
    };
    this.rafId = requestAnimationFrame(loop);
  }

  stop() {
    this.running = false;
    if (this.rafId) cancelAnimationFrame(this.rafId);
  }
}
